# Generated by Django 6.0.2 on 2026-03-13 00:00

from pathlib import Path
from uuid import uuid4

import django.db.models.deletion
from django.db import migrations, models


def profile_picture_upload_to(instance, filename):
    extension = Path(filename).suffix.lower()
    return f"profile_pictures/{uuid4().hex}{extension}"


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("QuestLog", "UserProfile")
    batch_size = 1000
    profiles = []

    for user in User.objects.all().iterator(chunk_size=batch_size):
        profiles.append(UserProfile(user_id=user.pk, display_name=user.username))
        if len(profiles) >= batch_size:
            UserProfile.objects.bulk_create(
                profiles,
                batch_size=batch_size,
                ignore_conflicts=True,
            )
            profiles = []

    if profiles:
        UserProfile.objects.bulk_create(
            profiles,
            batch_size=batch_size,
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=150)),
                ("profile_picture", models.ImageField(blank=True, upload_to=profile_picture_upload_to)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="auth.user",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_profiles_for_existing_users, migrations.RunPython.noop),
    ]
