# Generated by Django 6.0.2 on 2026-03-13 16:44

import QuestLog.utilities
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartySecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_secret_hash', models.CharField(editable=False, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_attributes', models.CharField(default='To be determined', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('party_name', models.CharField(max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='parties', to=settings.AUTH_USER_MODEL)),
                ('secret', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='questlog.partysecret')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Not started'), (1, 'In progress/Claimed'), (2, 'Completed')], default=0)),
                ('point_value', models.PositiveIntegerField(default=0)),
                ('proofs', models.FileField(blank=True, null=True, upload_to=QuestLog.utilities.secure_upload_path_proofs, validators=[QuestLog.utilities.validate_upload, QuestLog.utilities.scan_for_malicious_code, QuestLog.utilities.validate_image_file, QuestLog.utilities.validate_content_type])),
                ('recurring', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questlog.party')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('avatar', models.FileField(blank=True, null=True, upload_to=QuestLog.utilities.secure_upload_path_avatars, validators=[QuestLog.utilities.validate_upload, QuestLog.utilities.scan_for_malicious_code, QuestLog.utilities.validate_image_file, QuestLog.utilities.validate_content_type])),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questlog.party')),
                ('rewards', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questlog.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
