# Generated by Django 6.0.2 on 2026-03-26 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestLog', '0004_dedupe_userpoints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userpoints',
            constraint=models.UniqueConstraint(fields=('user', 'party'), name='unique_user_points_per_party'),
        ),
    ]
