# Generated by Codex on 2026-04-09

import django.db.models.deletion
from django.db import migrations, models


def align_postgres_userprofile_primary_key(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return

    UserProfile = apps.get_model("QuestLog", "UserProfile")
    configured_table_name = UserProfile._meta.db_table

    with connection.cursor() as cursor:
        table_names = {
            table_name.lower(): table_name
            for table_name in connection.introspection.table_names(cursor)
        }
        table_name = table_names.get(configured_table_name.lower())
        if not table_name:
            return

        columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        }
        if "id" not in columns:
            return

        quote_name = schema_editor.quote_name
        constraints = connection.introspection.get_constraints(cursor, table_name)
        for constraint_name, constraint in constraints.items():
            if constraint.get("primary_key"):
                schema_editor.execute(
                    f"ALTER TABLE {quote_name(table_name)} "
                    f"DROP CONSTRAINT {quote_name(constraint_name)}"
                )

        schema_editor.execute(
            f"ALTER TABLE {quote_name(table_name)} DROP COLUMN {quote_name('id')}"
        )
        schema_editor.execute(
            f"ALTER TABLE {quote_name(table_name)} "
            f"ADD PRIMARY KEY ({quote_name('user_id')})"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("QuestLog", "0005_userpoints_unique_user_points_per_party"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    align_postgres_userprofile_primary_key,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="userprofile",
                    name="id",
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="user",
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to="auth.user",
                    ),
                ),
            ],
        ),
    ]
