# Generated by Django 6.0.2 on 2026-04-26 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestLog', '0007_task_difficulty_rating_task_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty_rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='taskdifficultyvote',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
