# Generated by Django 5.0.4 on 2026-05-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QuestLog", "0008_alter_task_difficulty_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="fantasy_description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="fantasy_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
