# Generated by Django 6.0.2 on 2026-05-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestLog', '0008_alter_task_difficulty_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bounty',
            field=models.PositiveIntegerField(default=0, help_text='Extra points funded by the task creator, paid out to whoever completes this task.'),
        ),
    ]
