"""Merge task fantasy fields and user point spending migrations."""

# pylint: disable=invalid-name

# Generated by Django 6.0.2 on 2026-05-02 21:36

from django.db import migrations


class Migration(migrations.Migration):
    """Merge task fantasy fields with user point spending."""

    dependencies = [
        ('QuestLog', '0009_task_fantasy_description_task_fantasy_name'),
        ('QuestLog', '0011_userpoints_spent_points'),
    ]

    operations = [
    ]
