# Generated by Django 6.0.2 on 2026-05-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestLog', '0011_repair_task_difficulty_schema'),
        ('QuestLog', '0011_userpoints_spent_points'),
    ]

    operations = [
    ]
