# Generated by Django 6.0.2 on 2026-05-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestLog', '0012_merge_20260502_2106'),
        ('QuestLog', '0012_merge_20260502_2136'),
    ]

    operations = [
    ]
